config/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('', base_views.Index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

admin.site.site_header="Qsub Pages" # 로그인 전 "Djanggo 관리" 라는 Text 변경
admin.site.site_title="Qsub Pages" # 로그인 후 상단 배너의 "Djanggo 관리" 라는 Text 변경

handler404 = 'common.views.page_not_found' # handelr404 변수를 설정하면 404 오류 발생시 사용자가 정의한 뷰 함수를 호출 여기선 common/views.py의 page_not_found 함수를 호출

pybo/urls.py
from collections import namedtuple
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views, apttrade_views

app_name='pybo'
urlpatterns =[
    # name attribute는 별칭으로, 별칭을 사용함에 따라, html에 url 호출 시 하드코딩을 피함. 추후 URL 변경시 유지보수 용이
    
    #base_views.py
    path('', base_views.Index, name='index'),
    path('<int:question_id>/', base_views.DetailView, name='detail'), 
    
    #question_views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    #answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer, name='comment_delete_answer'),

    #vote_views
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),

    #아파트 실거래가 조회
    path('life/apttrade/', apttrade_views.apttrade, name="apttrade"),
]

pybo/models.py
from django.db import models
from common.models import CustomUser

# Create your models here.

# Category model 추가
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)

class Question(models.Model):
    author=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author_question')
    subject=models.CharField(max_length=200)
    content=models.TextField()
    content_summary=models.TextField()
    create_date=models.DateTimeField()
    modify_date=models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_question')
    category = models.CharField(max_length=255, default='문의글', blank=True)
    viewCount = models.IntegerField(default=0, blank=True)
    avatar = models.CharField(max_length=200, null=True, blank=True, default=None)

    def __str__(self):
        return str(self.id)

class Answer(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date=models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_answer')
    avatar = models.CharField(max_length=200, null=True, blank=True, default=None)

    def __str__(self):
        resultText = str(self.question) + '/' + self.content 
        return resultText 

class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)


class Citycode(models.Model):
    code=models.IntegerField()
    provins= models.TextField()
    city=models.TextField()

    def __str__(self):
        return str(self.code)

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnwserForm
from ..models import Answer, Question

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question=get_object_or_404(Question, pk=question_id)

    if request.method=="POST":
        form = AnwserForm(request.POST)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.author=request.user
            answer.create_date=timezone.now()
            answer.question=question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id ))
            #.resolve_url 함수는 실제 호출되는 URL을 문자열로 반환하는 장고 함수
    else:
        form=AnwserForm()
    context = {'question':question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method=="POST":
        form = AnwserForm(request.POST, instance=answer)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.author=request.user
            answer.modify_date=timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form=AnwserForm(instance=answer)
    context={'answer':answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    """
    답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    else:
        answer.delete()
    return redirect('pybo:detail',question_id=answer.question.id)

pybo/views/apttrade_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

#실거래가 정보를 가지고 오기 위해 필요한 모듈
from urllib.request import urlopen, Request
from urllib import parse
import requests

@login_required(login_url='common:login')
def apttrade(request):
    return render(request, 'pybo/apttrade.html', None)


@login_required(login_url='common:login')
def apttradeinfo(request):
    serviceKey="C0mz/4Z5ocwKxiaIzhh3wgLTzXaqXVOecq8yJ9jnUVWLA5E9VvP0Dy36zP851OOQSKGf8qjS6d9tA2tnnELdTg=="

    url =  'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade'
    queryParams = parse.urlencode({"ServiceKey" : serviceKey, "LAWD_CD":"11110", "DEAL_YMD": "201512"})
    #queryParams = '?' + parse.urlencode({ parse.quote_plus('ServiceKey') : serviceKey, parse.quote_plus('LAWD_CD') : '11110', parse.quote_plus('DEAL_YMD') : '201512' })
    request = requests.get(url, params=queryParams)

    #request = Request(url+queryParams)

    #request.get_method = lambda: 'GET'
    #response_body = urlopen(request).read()
    print (request.text)

pybo/views/apttradeinfo_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

#실거래가 정보를 가지고 오기 위해 필요한 모듈
from urllib.request import urlopen, Request
from urllib import parse
import requests


@login_required(login_url='common:login')
def apttradeinfo(request):
    serviceKey="C0mz/4Z5ocwKxiaIzhh3wgLTzXaqXVOecq8yJ9jnUVWLA5E9VvP0Dy36zP851OOQSKGf8qjS6d9tA2tnnELdTg=="

    url =  'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade'
    queryParams = parse.urlencode({"ServiceKey" : serviceKey, "LAWD_CD":"11110", "DEAL_YMD": "201512"})
    #queryParams = '?' + parse.urlencode({ parse.quote_plus('ServiceKey') : serviceKey, parse.quote_plus('LAWD_CD') : '11110', parse.quote_plus('DEAL_YMD') : '201512' })
    request = requests.get(url, params=queryParams)

    #request = Request(url+queryParams)

    #request.get_method = lambda: 'GET'
    #response_body = urlopen(request).read()
    print (request.text)

pybo/views/base_views.py
from django.views import generic
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Answer, Question

import logging

logger = logging.getLogger('pybo')

def Index(request): # request는 사용자가 전달한 데이터를 확인 할 때 사용 된다.

    """
    pybo 목록 출력
    """
    page = request.GET.get('page', '1') # 페이지
    kw = request.GET.get('kw', '')      # 검색어
    so = request.GET.get('so', 'recent')      # 정렬기준

    #정렬
    if so == 'recommend':
        question_list=Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list=Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list=Question.objects.order_by('-create_date')

    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw) | #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) #답변 글쓴이 검색
            # contains 대신 icontains를 사용하게 되면 대소문자를 가리지 않고 찾아 줌
            # filter 함수에서 모델 필드에 접근하려면 __ 를 이용하면 된다.
        ).distinct() # 중복 제거

    paginator=Paginator(question_list, 5)
    page_obj=paginator.get_page(page)

    context={'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}

    return render(request, 'pybo/question_list.html', context)

def DetailView(request, question_id):
    """
    pybo 내용 출력
    """
    page = request.GET.get('page', '1') # 페이지

    question=Question.objects.get(id=question_id)
    question.viewCount = question.viewCount + 1
    question.save()
        
    answer_list = question.answer_set.all() \
        .annotate(num_voter=Count('voter')) \
        .order_by('-num_voter', '-create_date')

    paginator=Paginator(answer_list, 10)
    page_obj=paginator.get_page(page)

    
    context={'question':question, 'answer_list':page_obj, 'page':page}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Comment, Question, Answer

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.question=question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=question.id), comment.id))
    else:
        form=CommentForm
    context ={'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문 댓글 수정
    """

    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', pk=comment.question.id)

    if request.method =="POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.modify_date=timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
      form=CommentForm(instance=comment)

    context={'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request,comment_id):
    """
    pybo
    질문 댓글 삭제
    """

    comment=get_object_or_404(Comment,pk=comment_id)

    if (request.user != comment.author):
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답변 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.answer=answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), comment.id))
    else:
        form=CommentForm
    context ={'form':form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답변 댓글 수정
    """

    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.id)

    if request.method =="POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.modify_date=timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
      form=CommentForm(instance=comment)

    context={'form':form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request,comment_id):
    """
    pybo
    답변 댓글 삭제
    """

    comment=get_object_or_404(Comment,pk=comment_id)

    if (request.user != comment.author):
        messages.error(request, '댓글 삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Answer, Question

@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        if list(filter(lambda a : a==request.user, question.voter.all())):
            messages.error(request, '추천은 한번만 할 수 있습니다.')
        else:
            question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답변 추천 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        if list(filter(lambda a : a==request.user, answer.voter.all())):
            messages.error(request, '추천은 한번만 할 수 있습니다.')
        else:
            answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/pybo/apttrade.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <form action="#" method="POST" class="my-3">
        <label for="month">조회 연/월</label>
        <input type="month" id="month" class="form-control input-lg" style="width: 200px;" />

    </form>
    

    
</div>
<script text="text/javascript">
    var today = new Date();
    month = (today.getMonth()+1).toString().padStart(2,'0');
    maxdate = today.getFullYear()+'-'+month;
    document.getElementById("month").max = maxdate;
    document.getElementById("month").value = maxdate;
</script>


"

<!-- GIJGO date picker 사용시
    <input id="datepicker" width="276" />
    <script>
        $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            iconsLibrary: 'fontawesome',
            format: 'mm yyyy',
            footer : true,
            header: true,
            modal:true
        });
    </script>-->

{%endblock%}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="contnet">댓글내용</label>
            <textarea class="form-control" name="content" id="contnet" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div class="container my-3">
    <!--사용자 오류 포시-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{message.tag}}</strong>
        <ul><li>{{message.message}}</li></ul>
        {% endfor %}
    </div>
    {%endif%}
    <h2 class="border-bottom py-2">{{ question.subject  }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!--추천 영역-->
            <div class="bg-light text-center p-3 border font-wehgith-bolder mb-1">
                {{ question.voter.count}}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"><!--질문 영역-->
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text">{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{question.author.username}}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                            <a name="comment_{{comment.id}}"></a>
                            <div class="comment py-2 text-muted">
                                <span style="white-space: pre-line;">{{ comment.content }}</span>
                                <span>
                                    - {{comment.author}}, {{comment.create_date}}
                                    {% if comment.modify_date %}
                                    (수정:{{ comment.modify_date }})
                                    {% endif %}
                                </span>
                                {% if request.user == comment.author %}
                                <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
                                <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글추가</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>  
    <a name="anchor"></a> <!--답변에 적용된 페이징 기능에서 다음 페이지로 넘길때 위에 질문 내용이 안보이도록-->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{answer.id}}"></a>
    <div class="row my-3">
        <div class="col-1"><!--추천영역-->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ answer.voter.count}}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark}}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{answer.author.username}}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!--답변 댓글 Start-->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                        <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                -{{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date}})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id%}" class="small">수정</a>,
                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id%}">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {%endif%}
                    <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가</small></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!--페이지 리스트-->
        {% for page_number in answer_list.paginator.page_range %}
        {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
            {% if page_number == answer_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{page_number}}" href="#">{{page_number}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{page_number}}" href="#">{{page_number}}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음페이지-->
        {% if answer_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{answer_list.next_page_number}}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징 처리 종료-->
    <form action="{% url 'pybo:answer_create' question.id %}" method="POST" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <textarea name="content" id="content" {%if not user.is_authenticated %}disabled{%endif%} class="form-control" rows="10"></textarea>
        <input type="submit" value="답변등록" class="btn btn-primary my-2"></input>
    </form>
</div>
<form id="searchForm" method="GET" action="#anchor">
    <input type="hidden" id="page" name="page" value="{{page}}">
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").on('click', function(){
        if(confirm("정말로 삭제하시겠습니까?")){
            location.href=$(this).data('uri');
        }
    });

    $(".recommend").on('click', function(){
        if(confirm("정말로 추천하시겠습니까?")){
            location.href=$(this).data('uri');
        }
    });

    $(".page-link").on('click', function(){
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
    });

})
</script>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- {{form.as_p}} -->
        <!-- 오류표시 해보자 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong> {{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 end -->
        <div class="form-group">
            <lable for="subject">제목</lable>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <lable for="category">카테고리</lable>
            <select class="form-control" name="dropbox">
                {% for category in category_list %}
                <option value="{{ category }}">{{category}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}