common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='common'

urlpatterns=[
    #as_view() 괄호 안에 template_name을 사용하여 login.html을 참조할 위치를 정해 줄 수 있다.
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('singup/', views.signup, name="signup"),
    path('userprofile/', views.userprofile, name="userprofile"),
    path('changePW/', views.changePW, name="changePW"),
    path('kakaoLogin/', views.kakaoLogin, name="kakaoLogin"),
    path('kakaoOauth/', views.kakaoOauth, name="kakaoOauth"),
    path('logoutPre/', views.logoutPre, name='logoutPre')
]

config/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('', base_views.Index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

admin.site.site_header="Qsub Pages" # 로그인 전 "Djanggo 관리" 라는 Text 변경
admin.site.site_title="Qsub Pages" # 로그인 후 상단 배너의 "Djanggo 관리" 라는 Text 변경

handler404 = 'common.views.page_not_found' # handelr404 변수를 설정하면 404 오류 발생시 사용자가 정의한 뷰 함수를 호출 여기선 common/views.py의 page_not_found 함수를 호출

pybo/urls.py
from collections import namedtuple
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views, apttrade_views

app_name='pybo'
urlpatterns =[
    # name attribute는 별칭으로, 별칭을 사용함에 따라, html에 url 호출 시 하드코딩을 피함. 추후 URL 변경시 유지보수 용이
    
    #base_views.py
    path('', base_views.Index, name='index'),
    path('<int:question_id>/', base_views.DetailView, name='detail'), 
    
    #question_views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    #answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer, name='comment_delete_answer'),

    #vote_views
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),

    #아파트 실거래가 조회
    path('life/apttrade/', apttrade_views.apttrade, name="apttrade"),
]

common/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models
from . import managers

# Create your models here.

class CustomUser(AbstractUser):

    """ Custom User model """

    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_KAKAO, "Kakao"),
    )

    login_method = models.CharField(
        max_length=6, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    access_token = models.CharField(max_length=100, null=True, blank=True)
    avatar = models.CharField(max_length=200, null=True, blank=True, default=None)

    objects = managers.CustomUserModelManager()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model=User
        fields =("username", "email")

#UserCreationForm
#은 기본적으로 username과 password1, password2(Password1과 대조하기 위한 값) 을 기본속성으로 가진다.
#Email 속성을 추가하기 위해 UserCreationFrom을 상속하는 UserForm을 새로 만든 것

common/views.py
import json
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth import hashers
from django.contrib.auth import models
from django.contrib.auth.hashers import check_password
from .models import CustomUser
from django.core import exceptions
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib import messages
from django.shortcuts import redirect


from pathlib import Path
import os, json, requests
from django.core.exceptions import ImproperlyConfigured
# Create your views here.

##########  전역 변수  ##########
BASE_DIR = Path(__file__).resolve().parent.parent
secret_file = os.path.join(BASE_DIR, 'secrets.json')
###### 카카오 REST_API_KEY를 가지고 온다 ######
try:
    with open(secret_file) as f:
            secrets=json.loads(f.read())
            REST_API_KEY = secrets["REST_API_KEY"]
            REDIRECT_URI = secrets["REDIRECT_URL"]
except KeyError:
    error_msg="Set the {} environment variable".format("REST_API_KEY")
    raise ImproperlyConfigured(error_msg)
##########################################

def signup(request):
    """
    회원가입
    """
    if request.method =="POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            raw_password=form.cleaned_data.get('password1')
            user=authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form=UserForm()
    return render(request, 'common/signup.html',{'form':form})

# 사용자 프로필 보기
def userprofile(request):

    return render(request, 'common/userprofile.html', None)

# 사용자 패스워드 변경
def changePW(request):

    if request.method=="POST":
        user = CustomUser.objects.get(username=request.user.username)
        current_pw=request.POST.get('password', None)
        if check_password(current_pw, user.password):
            new_password1 = request.POST.get('password1', None)
            new_password2 = request.POST.get('password2', None)
            if new_password1 == new_password2:
                user.set_password(new_password1)
                user.save()
                login(request,user)
                messages.info(request, "새로운 비밀번호로 변경 되었습니다.")
                return redirect('index')
            else:
                messages.error(request, "새로운 비밀번호 입력 값이 일치하지 않습니다.")
                return render(request, 'common/userprofile.html', {'PWerror' : 'PWerror'})

        else:
            messages.error(request, "현재 비밀번호가 일치하지 않습니다.")
            return render(request, 'common/userprofile.html', {'PWerror' : 'PWerror'})

def kakaoLogin(request):

    try:
        if request.user.is_authenticated:
            raise KakaoException("User already logged in")
      
        API_HOST = f'https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code'
        f.close()
    except KakaoException as error:
        messages.error(request, error)
        return redirect('index')

    return redirect(API_HOST)


def kakaoOauth(request):
    # 로그인에 성공하게 되면 내가 redirect_uri로 설정한 https://qsub.co.kr/kakaoOauth에
    # code 가 붙어서 오며 이 코드를 가지고 사용자 정보를 얻기 위한 Access Token을 발급 받는다.
    try:
        CODE = request.GET.get('code', None)

        if CODE is None:
            raise KakaoException("Can't get CODE")

        API_HOST = f'https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={CODE}'
        f.close()
        request_access_token=requests.post(API_HOST, headers={"Accept":"application/json"},)
        access_token_json = request_access_token.json()
        error = access_token_json.get("error", None)
        if error is not None:
            print(error)
            KakaoException("Can't get access token")
        
        access_token = access_token_json.get("access_token")

        headers = {"Authorization": f"Bearer {access_token}"}
        user_profile = requests.post("https://kapi.kakao.com/v2/user/me", headers=headers,)

        profile_json = user_profile.json()
        kakao_account = profile_json.get("kakao_account")
        profile = kakao_account.get("profile")

        nickname = profile.get("nickname", None)
        avatar_url = profile.get("profile_image_url", None)
        emailinfo = kakao_account.get("email", None)
        if emailinfo is None:
            emailinfo = nickname

        user = CustomUser.objects.get_or_none(email=emailinfo)
        
        if user is None:
            user = CustomUser.objects.create_user(
                email=emailinfo,
                username=emailinfo,
                first_name=nickname,
                login_method=CustomUser.LOGIN_KAKAO,
                access_token= access_token,
                avatar = avatar_url,
            )
            user.set_unusable_password()
            user.save()
        else:
            user.avatar = avatar_url
            user.access_token= access_token
            user.save()


        messages.success(request, "카카오톡 계정을 통하여 로그인 하셨습니다.")
        login(request, user)
        return redirect('index')


    except KakaoException as error:
        messages.error(request, error)
        return redirect('index')

def logoutPre(request):
    try:
        user=CustomUser.objects.get(username=request.user.username)
        access_token = user.access_token
        if access_token is not None:
            user.access_token = None
            user.save()
            headers = {"Authorization": f"Bearer {access_token}"}
            response= requests.post("https://kapi.kakao.com/v1/user/logout", headers=headers)
            print(response)

        return redirect("common:logout")
    except:
        pass

        


# 찾는 페이지가 없는 경우 404 로 이동한다.
def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})

# 카카오톡 에러처리를 위하여 exceptions을 상속 받은 클래스를 생성해준다.
class KakaoException(Exception):
    pass

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="pt-5 pb-5 mt-0 align-items-center d-flex bg-dark"
    style="min-height: 100vh; background-size: cover; background-image: url(https://images.unsplash.com/photo-1477346611705-65d1883cee1e?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1920&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=c0d43804e2c7c93143fe8ff65398c8e9);">
    <div class="container-fluid">
        <div class="row  justify-content-center align-items-center d-flex-row text-center h-100">
            <div class="col-12 col-md-4 col-lg-3   h-50 ">
                <div class="card shadow">
                    <div class="card-body mx-auto">
                        <h4 class="card-title mt-3 text-center">로그인</h4>
                        <form method="POST" class="post-form" action="{% url 'common:login' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{next}}">
                            {% include "form_errors.html" %}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                </div>
                                <input type="text" class="form-control" name="username" placeholder="사용자 이름" id="username" value="{{ form.username.value|default_if_none:'' }}">
                            </div>
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                <input type="password" class="form-control" name="password" id="password" placeholder="비밀번호" value="{{ form.password1.value|default_if_none:'' }}">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">로그인</button>
                            </div>
                            <p class="text-muted font-weight-bold ">
                                <span>혹은</span>
                            </p>
                            <p class="text-center"><i class="fas fa-share-alt-square"> 소셜미디어로 로그인</i></p>
                            <p>
                                <a href="{% url 'common:kakaoLogin' %}"><img src="{% static 'images/kakao_login.png' %}"></a>
                            </p>
                            <p class="text-center">아직 계정이 없으신가요?
                                <a href="{% url 'common:signup' %}">Sign Up</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section class="pt-5 pb-5 mt-0 align-items-center d-flex bg-dark"
    style="min-height: 100vh; background-size: cover; background-image: url(https://images.unsplash.com/photo-1477346611705-65d1883cee1e?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1920&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=c0d43804e2c7c93143fe8ff65398c8e9);">
    <div class="container-fluid">
        <div class="row  justify-content-center align-items-center d-flex-row text-center h-100">
            <div class="col-12 col-md-4 col-lg-3   h-50 ">
                <div class="card shadow">
                    <div class="card-body mx-auto">
                        <h4 class="card-title mt-3 text-center">회원 가입</h4>                       
                        <form method="post" class="post-form">
                            {% csrf_token %}
                            {% include "form_errors.html" %}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                </div>
                                <input type="text" class="form-control" name="username" placeholder="사용자 이름" id="username" value="{{ form.username.value|default_if_none:'' }}">
                            </div>
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                                </div>
                                <input type="email" class="form-control" name="email" id="email" placeholder="Email 주소" value="{{ form.email.value|default_if_none:'' }}">
                            </div>
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                <input type="password" class="form-control" name="password1" id="password1" placeholder="비밀번호" value="{{ form.password1.value|default_if_none:'' }}">
                            </div>
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                <input type="password" class="form-control" name="password2" id="password2" placeholder="비밀번호 확인" value="{{ form.password2.value|default_if_none:'' }}">    
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">생성하기</button>
                            </div>
                            <p class="text-muted font-weight-bold ">
                                <span>혹은</span>
                            </p>
                            <p class="text-center"><i class="fas fa-share-alt-square"> 소셜미디어로 로그인</i></p>
                            <p>
                                <a href="{% url 'common:kakaoLogin' %}"><img src="{% static 'images/kakao_login.png' %}"></a>
                            </p>
                            <p class="text-center">이미 계정을 가지고 있으신가요?
                                <a href="{% url 'common:login' %}">Log In</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/common/userprofile.html
{% extends 'base.html' %}

{% block content %}
<section class="pt-5 pb-5 mt-0 align-items-center d-flex bg-dark"
    style="min-height: 100vh; background-size: cover; background-image: url(&quot;https://images.unsplash.com/photo-1517216015940-049a2d4e2da4?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=14035a7d76df29c4697de036fcd005ce&quot;);">
    <div class="container-fluid">
        <div class="row  justify-content-center align-items-center d-flex-row h-100">
            <div class="col-12 col-md-8 col-lg-8   h-50 ">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="card">
                            <div class="card-header">
                                <ul class="nav nav-tabs card-header-tabs" id="profile-list" role="tablist">
                                    <li class="nav-item"><a class="nav-link {%if not PWerror%}active{%endif%}" href="#userdetail" data-toggle="tab"><i class="fas fa-id-card"> 사용자 정보</i></a></li>
                                    {% if user.login_method != 'kakao' %}
                                    <li class="nav-item"><a class="nav-link {%if PWerror%}active{%endif%}" href="#pwchange" data-toggle="tab"><i class="fas fa-lock"> 비밀번호 변경</i></a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content">
                                    <div id="userdetail" class="tab-pane fade {% if not PWerror %}show active{%endif%}">
                                        <h5><i class="fas fa-portrait"> 사용자명 (ID)</i></h5><input type="text" style="transform: scale(1);width: 100%;height: 30px;margin-bottom: 30px; margin-top: 10px;" value="{{user.username}}" disabled>
                                        <h5 style="margin-top: 0;"><i class="fas fa-envelope"> 이메일(E-Mail)</i></h5><input type="text" style="transform: scale(1);width: 100%;height: 30px;margin-bottom: 30px; margin-top: 10px;" value="{{user.email}}" disabled>
                                    </div>
                                    <div id="pwchange" class="tab-pane fade {%if PWerror%}show active{%endif%}">
                                        {% if messages %}
                                        <div class="alert alert-danger my-3" role="alert">
                                            {% for message in messages %}
                                            <strong>{{message.tag}}</strong>
                                            <ul><li>{{message.message}}</li></ul>
                                            {% endfor %}
                                        </div>
                                        {%endif%}
                                        <form method="post" class="form-group" action="{% url 'common:changePW' %}">
                                            {% csrf_token %}
                                            {% include "form_errors.html" %}
                                            <h6 style="margin-top: 10;"><i class="fas fa-lock"> 기존 비밀번호</i></h6><input type="password" id="password" name="password" class="form-control" style="transform: scale(1);width: 100%;height: 30px;margin-bottom: 20px; margin-top: 5px;">
                                            <h6 style="margin-top: 10;"><i class="fas fa-lock"> 새 비밀번호</i></h6><input type="password" id="password1" name="password1" class="form-control" style="transform: scale(1);width: 100%;height: 30px;margin-bottom: 20px; margin-top: 5px;">
                                            <h6 style="margin-top: 10;"><i class="fas fa-lock"> 새 비밀번호 (확인)</i><input type="password" id="password2" name="password2" class="form-control" style="transform: scale(1);width: 100%;height: 30px;margin-bottom: 20px; margin-top: 5px;">
                                            <button class="btn btn-primary" type="summit"><i class="fa fa-save"></i>&nbsp;저장하기</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}