common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='common'

urlpatterns=[
    #as_view() 괄호 안에 template_name을 사용하여 login.html을 참조할 위치를 정해 줄 수 있다.
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('singup/', views.signup, name="signup"),
    path('userprofile/', views.userprofile, name="userprofile"),
    path('changePW/', views.changePW, name="changePW"),
    path('kakaoLogin/', views.kakaoLogin, name="kakaoLogin"),
    path('kakaoOauth/', views.kakaoOauth, name="kakaoOauth"),
    path('logoutPre/', views.logoutPre, name='logoutPre')
]

config/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('', base_views.Index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

admin.site.site_header="Qsub Pages" # 로그인 전 "Djanggo 관리" 라는 Text 변경
admin.site.site_title="Qsub Pages" # 로그인 후 상단 배너의 "Djanggo 관리" 라는 Text 변경

handler404 = 'common.views.page_not_found' # handelr404 변수를 설정하면 404 오류 발생시 사용자가 정의한 뷰 함수를 호출 여기선 common/views.py의 page_not_found 함수를 호출

pybo/urls.py
from collections import namedtuple
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views, apttrade_views

app_name='pybo'
urlpatterns =[
    # name attribute는 별칭으로, 별칭을 사용함에 따라, html에 url 호출 시 하드코딩을 피함. 추후 URL 변경시 유지보수 용이
    
    #base_views.py
    path('', base_views.Index, name='index'),
    path('<int:question_id>/', base_views.DetailView, name='detail'), 
    
    #question_views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    #answer_views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer, name='comment_delete_answer'),

    #vote_views
    path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),

    #아파트 실거래가 조회
    path('life/apttrade/', apttrade_views.apttrade, name="apttrade"),
]

pybo/views/base_views.py
from django.views import generic
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Answer, Question

import logging

logger = logging.getLogger('pybo')

def Index(request): # request는 사용자가 전달한 데이터를 확인 할 때 사용 된다.

    """
    pybo 목록 출력
    """
    page = request.GET.get('page', '1') # 페이지
    kw = request.GET.get('kw', '')      # 검색어
    so = request.GET.get('so', 'recent')      # 정렬기준

    #정렬
    if so == 'recommend':
        question_list=Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list=Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list=Question.objects.order_by('-create_date')

    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw) | #질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) #답변 글쓴이 검색
            # contains 대신 icontains를 사용하게 되면 대소문자를 가리지 않고 찾아 줌
            # filter 함수에서 모델 필드에 접근하려면 __ 를 이용하면 된다.
        ).distinct() # 중복 제거

    paginator=Paginator(question_list, 5)
    page_obj=paginator.get_page(page)

    context={'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}

    return render(request, 'pybo/question_list.html', context)

def DetailView(request, question_id):
    """
    pybo 내용 출력
    """
    page = request.GET.get('page', '1') # 페이지

    question=Question.objects.get(id=question_id)
    question.viewCount = question.viewCount + 1
    question.save()
        
    answer_list = question.answer_set.all() \
        .annotate(num_voter=Count('voter')) \
        .order_by('-num_voter', '-create_date')

    paginator=Paginator(answer_list, 10)
    page_obj=paginator.get_page(page)

    
    context={'question':question, 'answer_list':page_obj, 'page':page}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--Font Awesome 5 CDN-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- GIJGO Datepicker
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />-->

  
    <title>Welcome</title>
  </head>
  <body>
    {% include "navbar.html" %}
    {% block content %}

    {% endblock %}

    <!--Boot Strap & Jquery-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    {% block script %}
    {% endblock %}

  </body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %} <!--field 오류를 출력한다.-->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--네비게이션바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" style="min-height: 70px;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pybo:index' %}"><h3><i class="fab fa-python"> Qsub's Space</i></h3></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          생활 정보
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'pybo:apttrade'%}">부동산 실거래가</a>
          <a class="dropdown-item" href="#">코로나 현황</a>
          <a class="dropdown-item" href="#">미세먼지</a>
        </div>
      </li>
    </ul>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
      <ul class="navbar-nav" style="margin: 0px;">
        <li class="nav-item">
          {% if user.is_authenticated %}
            {%if user.avatar is not null %}
            <a class="nav-link" href="{% url 'common:userprofile'%}">
            <img style="
            border: 1px solid gold;
            border-radius: 70px;
            -moz-border-radius: 70px;
            -khtml-border-radius: 70px;
            -webkit-border-radius: 70px;
            " width="35px" height="35px" src={{user.avatar}}>
            {% else %}
            <a class="nav-link" href="{% url 'common:userprofile'%}" style="margin: 6px;">
            <i class="fas fa-user-alt">
              {% endif %}
              {{ user.username }}</i></a>
          {% else %}
            <a class="nav-link" href="{% url 'common:signup' %}"><i class="fas fa-user-plus"> 회원가입</i></a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logoutPre' %}" style="margin: 6px;"><i class="fas fa-sign-out-alt"> 로그아웃</i></a>
          {% else %}
            <a class="nav-link" href="{% url 'common:login' %}"><i class="fas fa-sign-in-alt"> 로그인</i></a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>